Update v1.0.1
Conctr/squirrel pull request #8
Opened 2017-01-13 05:01 UTC by sumeetrajpal

*sendData() now accepts a array of payloads.
*Posts an array to Conctr vs singular payloads.
*Sanity check on timestamps in the agent.
*Updated version number.

2017-01-13 05:30 UTC, blindman2k requested changes

2017-01-13 05:30 UTC, blindman2k commented on conctr.agent.class.nut
> +                }else if(("_ts" in v) && typeof v._ts == "number" && ((v._ts.tostring().len() <= 10) ? v._ts < MIN_TIME : v._ts < MIN_TIME*1000)){
Get the formatting/spacing right - space before `else` and after `if`.
Put brackets around the middle `==` statement.
The third statement there needs to be simplified or moved out into a variable. It's way too complex.
The log should say "Setting to time()".

2017-01-13 05:30 UTC, blindman2k commented on conctr.device.class.nut
> +                        if(_DEBUG){
Please correct all the `if(` and `}else` typos.

2017-01-13 05:30 UTC, blindman2k commented on conctr.device.class.nut
> +                _getWifis(function(wifis) {
Do you really want to call `_getWifis()` for every loops? I doubt it.

2017-01-14 03:41 UTC, sumeetrajpal commented
Made requested changes.

2017-01-16 13:36 UTC, blindman2k commented
I submitted a pull request to your repo sumeetrajpal. Merge that and then
merge that into this pull request.

2017-01-18 10:04 UTC, blindman2k approved these changes
I think we are finally there!

2017-01-18 10:05 UTC, merged