Changes based on feedback by Electric Imp
Conctr/squirrel pull request #9
Opened 2017-01-29 05:45 UTC by sumeetrajpal

-Updated version format (Also changed version number from 1.0.1 to 1.1.0 as changes to agent constructer are not backward compatible)
-Incorporated changes made in Electric imps master branch to the Readme.md file
-Included hyperlink to sign up page in setup instructions in Readme.md
-Tested email verification link not clickable bug has been fixed on Conctr
-Included more in depth instructions on where to find required data for constructor.
-Changed agent constructor to accept a Table of options as an optional parameter 
-Fixed inconsistency with setOpts and constructor arguments.

2017-01-29 10:59 UTC, blindman2k commented on README.md
> +The constructor takes three required parameters: your application ID, API key and model. These details can be found by navigating into your application on the Conctr platform, selecting on the *model
"*models* tab" should be "*Models* tab" and "example button" should be "*Example* button".
"*Squirell*" should be "*Squirrel*". "options" should be "*Options*".

2017-01-29 10:59 UTC, blindman2k commented on README.md
>  #require "conctr.agent.class.nut:1.0.0"
Need to update the version number.

2017-01-29 10:59 UTC, blindman2k commented on README.md
> +        // Handle error
Remove this comment and replace with an error log.
server.error("Failed to deliver to Conctr: " + error);

2017-01-29 10:59 UTC, blindman2k commented on README.md
> +        server.log("Data was successfully recieved by Conctr");
Replace "recieved" with "received".

2017-01-29 10:59 UTC, blindman2k commented on README.md
>  #require "conctr.device.class.nut:1.0.0"
Update version number.

2017-01-29 10:59 UTC, blindman2k commented on README.md
> +        // Handle error
Similar error log here.

2017-01-29 10:59 UTC, blindman2k commented on README.md
> +        server.log("Data was successfully recieved from the device by Conctr");
Replace "recieved" with "received".

2017-01-29 10:59 UTC, blindman2k commented on conctr.agent.class.nut
> +            payload = [payload];
The spaces where better. Not sure why you took them out again.

2017-01-29 10:59 UTC, blindman2k commented on conctr.agent.class.nut
>      static HOUR_SEC = 3600; // One hour in seconds
Rename HOUR_SEC to something like DEFAULT_LOC_INTERVAL.

2017-01-29 21:08 UTC, sumeetrajpal commented on conctr.agent.class.nut
> +            payload = [payload];
my auto formatter :) will update it to stop doing that.

2017-01-29 21:19 UTC, sumeetrajpal commented
@blindman2k made requested changes

2017-01-29 23:21 UTC, sumeetrajpal commented
@blindman2k Made requested changes and added a send method to the device class which will work with the same arguments as the agent.send function. Added the description to the readme for this as well.

2017-01-30 06:03 UTC, blindman2k requested changes
Minor tweaks left.

2017-01-30 06:03 UTC, blindman2k commented on README.md
> +conctr.send("any string", currentTempAndPressure, function(error, response) {
Take the callback out of this example but leave it in otherwise.
agent.send() doesn't support callbacks so it will be confusing.

2017-01-30 06:03 UTC, blindman2k commented on conctr.device.class.nut
> +        if ((typeof unusedKey == "table" || typeof unusedKey == "array") && (payload == null || typeof payload == "function")) {
We don't need these checks and swaps. Just call sendData.

2017-01-30 06:03 UTC, blindman2k commented on conctr.device.class.nut
>      static HOUR_SEC = 3600;
Replace HOUR_SEC with DEFAULT_LOC_INTERVAL as you did with the agent.

2017-01-30 21:01 UTC, sumeetrajpal commented
@blindman2k made minor tweaks

2017-01-30 23:35 UTC, sumeetrajpal commented
@blindman2k resolved the conflicts. Can i merge it in?

2017-02-01 12:13 UTC, blindman2k approved these changes

2017-05-29 06:14 UTC, marcstringer commented on README.md
> +| *callback* | Function | No | Function to be called on response from Conctr. The function should take two arguements, *error* and *response*. When no error occurred, the first arguement will be null
should probably have a callback table.
See: https://github.com/mysticpants/Wiznet_5500
e.g
This method triggers the supplied callback function when data is received. The callback takes the following parameters:
Key            | Data Type|Description 
----------  | ---------- | ----------
error           | String .     | An error message
response   |

2017-05-29 06:22 UTC, marcstringer commented on README.md
> +| *options.locEnabled* | Boolean | `true` | When enabled, location data will be automatically included with the data payload. |
inconsistent with Description ending in a full stop. I think it looks better without a full stop

2017-05-29 06:25 UTC, marcstringer commented on README.md
> +    };
move the }; left most to align

2017-05-29 06:28 UTC, marcstringer commented on conctr.device.lib.nut
> +    // Location recording parameters
Imp will probably want a comment description per parameter

2017-05-29 06:30 UTC, marcstringer commented on conctr.device.lib.nut
> +    //
add a description of what the function does

2017-05-29 06:32 UTC, marcstringer commented on conctr.device.lib.nut
> +    function _sendAgentOpts(opts) {
function description

2017-05-29 06:34 UTC, marcstringer commented on example/send_data_from_agent/agent.example.nut
> +// Example payload. This must contain fields relating to your conctr model.
rephrase:
This must contain the fields in your conctr model.

2017-05-29 06:42 UTC, marcstringer commented on example/send_data_from_device/device.example.nut
> +bull <- Bullwinkle(bullOpts);
Should +bull <- Bullwinkle(bullOpts);
go before 

+conctrOpts <- {
 +    "locEnabled": true,
 +    "locInterval": 3600,
 +    "locSendOnce": false,
 +    "locWakeReasons": [WAKEREASON_BLINKUP, WAKEREASON_PIN, WAKEREASON_NEW_SQUIRREL],
 +    "messageManager": bull
 +}

2017-05-29 06:46 UTC, marcstringer commented on tests/agent.test.nut
> +            // Ensure this payload matches your model
rephrase // Ensure this payload matches your model
to 
// Ensure the payload fields match your model fields

2017-05-29 06:48 UTC, marcstringer commented on tests/agent.test.nut
> +    function testSendData() {
you will want a header message explaining in a line what the test is doing.
e.g
// tests the sendData function receives the correct http response

2017-05-29 06:49 UTC, marcstringer commented on tests/agent.test.nut
> +                this.assertEqual(201, resp.statuscode);
201 is a magic number. should declare it at the top

2017-05-29 06:49 UTC, marcstringer commented on tests/agent.test.nut
> +                "temperature": 15,
worth also making the values of temperature i.e 15 a global constant so can be easily changed.

2017-05-29 06:52 UTC, marcstringer commented on tests/agent.test.nut
> +    function testSetDeviceId() {
header description

2017-05-29 06:53 UTC, marcstringer commented on tests/agent.test.nut
> +            this.assertTrue(conctr._device_id != newDeviceId);
is there a better test you could do here?
i.e what should conctr._devicde_id equal?

2017-05-29 06:53 UTC, marcstringer commented on tests/agent.test.nut
> +                this.assertEqual(401, resp.statuscode);
magic number 401

2017-05-29 06:54 UTC, marcstringer commented on tests/agent.test.nut
> +    function xtestRockyEndpoints() {
header. this 1 in particular as there are no comments through it

2017-05-29 06:55 UTC, marcstringer commented on tests/build_files/agent.in.nut
> +// #require "#require "messagemanager.class.nut:1.0.2"
should this line be here?

2017-05-29 06:56 UTC, marcstringer commented on tests/build_files/device.in.nut
> +// "#require "messagemanager.class.nut:1.0.2"
delete line? 
 +// "#require "messagemanager.class.nut:1.0.2"

2017-05-29 06:58 UTC, marcstringer commented on tests/device.test.nut
> +    function testSendData() {
Header function description + magic numbers

2017-05-29 06:59 UTC, marcstringer commented on tests/device.test.nut
> +                    this.assertEqual(201, resp.statuscode);
assertions in a promise. need to try and catch otherwise will crash the test

2017-05-29 06:59 UTC, marcstringer commented on tests/device.test.nut
> +    function testSend() {
header + magic numbers + assertions in a promse

2017-05-29 07:00 UTC, marcstringer commented on tests/device.test.nut
> +    function testSetLocationSendingOpts() {
header function description

2017-05-29 07:01 UTC, marcstringer commented on tests/device.test.nut
> +    function testSetLocationSendingOpts() {
+ assertions in a promise

2017-05-29 07:02 UTC, marcstringer commented on tests/device.test.nut
> +    function xtestMessageManagerReply() {
function header message + magic numbers + assertions in a promise

2017-06-07 00:48 UTC, marcstringer commented on README.md
>  The Conctr library allows you to easily integrate your agent and device code with the [Conctr IoT Platform](https://conctr.com). This library provides an easy way to send data to a Conctr application
Worth writing a couple of lines about what conctr is.

2017-06-07 00:53 UTC, marcstringer commented on README.md
> +### send(*ignoredString, payload*)
Example for send ?

2017-06-07 00:55 UTC, marcstringer commented on conctr.agent.lib.nut
> +    _api_key = null;
// Conctr Variables,  // Pending queue status, // Location state should have a single line comment

2017-06-07 01:29 UTC, marcstringer commented on conctr.agent.lib.nut
> +    //
This header doesnt have a return

2017-06-07 01:30 UTC, marcstringer commented on conctr.agent.lib.nut
> +    // Sends a request to the device to send its current location (array of wifis) if conditions in current location sending opts are met.
return in header

2017-06-07 01:31 UTC, marcstringer commented on conctr.agent.lib.nut
> +    // Claims a device for a consumer
return header

2017-06-07 01:31 UTC, marcstringer commented on conctr.agent.lib.nut
> +    //
return header

2017-06-07 01:32 UTC, marcstringer commented on conctr.device.lib.nut
> +    _locSent = false;
single likne comment for locsent and locTimeout

2017-06-07 01:35 UTC, marcstringer commented on conctr.agent.lib.nut
> +    //
return header this

2017-06-22 01:44 UTC, merged